spring:
  application:
    name: aandi_post_web_server
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      database: ${MONGO_DB_NAME}
      port: ${MONGO_PORT}
      uri: ${MONGO_DB_URL}

springdoc:
  swagger-ui:
    urls-primary-name: default
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true
server:
  forward-headers-strategy: framework