spring:
  application:
    name: aandi_post_web_server
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      database: ${MONGO_DB_NAME}
      port: ${MONGO_PORT}
      uri: ${MONGO_DB_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html