spring:
  application:
    name: aandi_post_web_server
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      host: mongodb-container
      database: aandi
      port: 27017

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html